name: Release

permissions:
  contents: write

on: [push]

defaults:
  run:
    shell: bash --noprofile --norc -CeEuo pipefail {0}

jobs:
  upload-assets:
    strategy:
      matrix:
        include:
          - target: x86_64-apple-darwin
            os: macos-15
          - target: aarch64-apple-darwin
            os: macos-15
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            RUSTFLAGS: -C target-feature=+crt-static
          - target: x86_64-pc-windows-gnu
            os: windows-latest
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-24.04
          - target: x86_64-unknown-linux-musl
            os: ubuntu-24.04
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: "-A warnings"
          toolchain: "stable"
      - uses: taiki-e/upload-rust-binary-action@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          bin: rquickjs
          target: ${{ matrix.target }}
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          RUSTFLAGS: ${{ matrix.RUSTFLAGS }}
